# Generated by Django 4.0.4 on 2022-06-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.FloatField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.combo')),
            ],
        ),
        migrations.CreateModel(
            name='Resurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('product_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('products', models.ManyToManyField(through='home_app.Product', to='home_app.combo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='resurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.resurs'),
        ),
    ]
