# Generated by Django 4.0.4 on 2022-06-12 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
